### ISSUE TITLE
OverflowError while using response.json with Gino models

### ISSUE THREAD

**Issue by snguyenthanh** [huge-success/sanic#1655] opened 2019-08-13 06:37 UTC
**Describe the bug**
`response.json` throws `OverflowError` with Gino.
Moreover, upon changing to `response.text`, there are no issues.

```
Traceback (most recent call last):
  File "/Users/.../.local/share/virtualenvs/venv/lib/python3.7/site-packages/sanic/app.py", line 942, in handle_request
    response = await response
  File "/Users/.../views/user.py", line 62, in user_route
    return response.json(data)
  File "/Users/.../.local/share/virtualenvs/venv/lib/python3.7/site-packages/sanic/response.py", line 234, in json
    dumps(body, **kwargs),
OverflowError: Maximum recursion level reached
Executing <Handle <TaskWakeupMethWrapper object at 0x10e549a98> created at /Users/.../.local/share/virtualenvs/.../lib/python3.7/site-packages/sanic/server.py:803> took 0.965 seconds
```

**Code snippet**
```
from sanic import response

@blueprint.route("/", methods=["GET", "POST"])
async def user_route(request):
    data = await User.query.gino.all()
    return response.json(data)
```

It seems to be because `data` is a `List` of Gino's models, instead of a `List` of `dict`.

Should `Sanic` raise a more detailed exception, like `unable to serialize the argument` ?

**Environment:**
- GINO version: 0.8.3
- Python version: 3.7.3
- asyncpg version: 0.18.3
- aiocontextvars version: 0.2.2
- PostgreSQL version: 11.4
- Sanic version: 19.6.2

**Comment by harshanarayana** [comment] 2019-08-13 08:05
@snguyenthanh 

`Gino` models have a `to_dict` helper available via `CRUDModel` Using that will fix your problem.

```python
data = await User.query.gino.all()
data = map(lambda u: u.to_dict(), data)
return json(data)
```

**Comment by snguyenthanh** [comment] 2019-08-13 17:05
Thanks @harshanarayana for the reply.
I was surprised when I got the `OverflowError` from `response.json`. And it took me some time to figure out it's a serialization error.

So I was thinking it may be helpful if the serialization error is handled by `Sanic` instead of building a custom handler.

However, if you think it is not necessary for `Sanic` to internally handle serialization errors, I'm okay with closing this issue.

**Comment by harshanarayana** [comment] 2019-08-14 09:34
@snguyenthanh but the cause of a serialization failure could be very large and varying based on contexts. So, handling them here as part of Sanic directly might become an additional performance overhead. They are probably better off being added as and when required during the implementation. This is just my personal opinion. 

Do not close the issue yet. Let the wider core Dev group take a final call on this

**Comment by ahopkins** [comment] 2019-08-27 06:32
I am in agreement with @harshanarayana. I am closing, but feel free to continue the conversation.

**Closed by ahopkins** 2019-08-27 06:32 UTC
