### ISSUE TITLE
Testing fails with ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by logileifs** [huge-success/sanic#1577] opened 2019-05-15 10:12 UTC
**Describe the bug**
After installing sanic and setting up tests like in the [documentation](https://sanic.readthedocs.io/en/latest/sanic/testing.html) and running them sanic fails with `ModuleNotFoundError: No module named 'aiohttp'`.

It succeeds after installing 'aiohttp' manually

**Code snippet**
Just do a clean install of sanic and create a test as in the documentation and try running it.

**Expected behavior**
If 'aiohttp' is a hard dependency for testing it should be included when installing sanic

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version sanic==19.3.1

**Stack trace**
```
Traceback (most recent call last):
  File "/home/logi/.virtualenvs/lemo3.6/lib/python3.6/site-packages/sanic/testing.py", line 97, in _collect_response
    method, url, *request_args, **request_kwargs
  File "/home/logi/.virtualenvs/lemo3.6/lib/python3.6/site-packages/sanic/testing.py", line 20, in _local_request
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by harshanarayana** [comment] 2019-05-15 10:45
@logileifs Can you please add the stack trace to the bug description?

**Comment by logileifs** [comment] 2019-05-15 10:47
`[2019-05-15 10:02:59 +0000] [8698] [INFO] Goin' Fast @ http://127.0.0.1:42101
[2019-05-15 10:02:59 +0000] [8698] [ERROR] Exception
Traceback (most recent call last):
  File "/home/logi/.virtualenvs/lemo3.6/lib/python3.6/site-packages/sanic/testing.py", line 97, in _collect_response
    method, url, *request_args, **request_kwargs
  File "/home/logi/.virtualenvs/lemo3.6/lib/python3.6/site-packages/sanic/testing.py", line 20, in _local_request
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
[2019-05-15 10:02:59 +0000] [8698] [INFO] Starting worker [8698]
[2019-05-15 10:02:59 +0000] [8698] [INFO] Stopping worker [8698]
[2019-05-15 10:02:59 +0000] [8698] [INFO] Server Stopped`

**Comment by harshanarayana** [comment] 2019-05-15 11:35
`aiohttp` is a `test` only package that doesn't get installed by default unless explicitly asked for. 

```bash
# Install sanic with test utilities
$ pip3 install "sanic[test]"
```

**Comment by harshanarayana** [comment] 2019-05-15 11:37
@logileifs  But I agree with what you mentioned under expected behavior. I think `aiohttp` can be moved to the default packages that get installed with `sanic` since we are using it with `testing.py` and this error feels unwarranted. 

@huge-success/sanic-core-devs  Any concerns moving `aiohttp` to the default packages installed?

**Comment by logileifs** [comment] 2019-05-15 11:40
> `aiohttp` is a `test` only package that doesn't get installed by default unless explicitly asked for.
> 
> ```shell
> # Install sanic with test utilities
> $ pip3 install "sanic[test]"
> ```

Is this documented anywhere? I believe I've read the documentation rather well and I don't recall seeing anywhere mentioned that sanic provides any extra packages

**Comment by harshanarayana** [comment] 2019-05-15 11:47
@logileifs  There is a reference for this under the `Contributing` section. But the command used in that context is a bit different since it installs sanic from a cloned path into. `pip install -e ".[test]"`

**Comment by ahopkins** [comment] 2019-05-15 12:12
`aiohttp` has been removed as of #1562. Instead, we have migrated to `requests-async`. The reason is primarily to support our development towards ASGI support (See #1475).

I do not think we should include it in the standard install because it is an extra dependency that is not **needed**. However, on the flip side, I think having `pip3 install "sanic[test]"` be documented is definitely worth doing to let people know that it is probably what they want in dev.

I also would highly push developers towards: https://github.com/yunstanford/pytest-sanic.

**Comment by logileifs** [comment] 2019-05-15 12:23
> I do not think we should include it in the standard install because it is an extra dependency that is not needed.

I disagree with you there @ahopkins, to develop a web application you need to be able to test it, to test it you apparently need `aiohttp` or `requests-async` so those dependencies should absolutely be included in the main package

**Comment by ahopkins** [comment] 2019-05-15 12:34
@logileifs In this case, then, your build packages and containers become bloated with unused code and unused dependencies.

**Comment by logileifs** [comment] 2019-05-15 12:45
@ahopkins fair enough

**Comment by harshanarayana** [comment] 2019-05-15 14:12
@logileifs `aiohttp` or `requests-async` are used as a dependency in `sanic` code as a way to test the `sanic` itself. 

If you are testing your own service written using `sanic` then `pytest-sanic` might be a more suitable way to perform your testing and that should install all the dependencies required to run the UTs and any other form of tests. 

@ahopkins You are right. Now that I think about it again after reading your comments, it should be enough to document this rather than moving it to the default list of dependencies installed. Thanks for pointing me in the right direction.

**Closed** 2019-05-16 16:48 UTC
Labels: documentation
