### ISSUE TITLE
Breaking change in Websocket 6.0 release

### ISSUE THREAD

**Issue by jamesstidard** [huge-success/sanic#1264] opened 2018-07-18 10:57 UTC
Hi,

Just pipenv installed sanic and it pulled down the new [websocket](https://github.com/aaugustin/websockets) 6.0 release. Making a simple websocket server will now throw a `AttributeError` on connection of a websocket client.

Here's a simple websocket sanic app along with the stack trace.

```python
from sanic import Sanic

app = Sanic()

@app.websocket('/feed')
async def feed(request, ws):
    while True:
        data = 'hello!'
        print('Sending: ' + data)
        await ws.send(data)
        data = await ws.recv()
        print('Received: ' + data)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

Here's the stack trace produced:

```
[2018-07-18 11:39:04 +0100] [63160] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2018-07-18 11:39:04 +0100] [63160] [INFO] Starting worker [63160]
[2018-07-18 11:39:06 +0100] [63160] [ERROR] Traceback (most recent call last):
  File "venv/lib/python3.7/site-packages/sanic/app.py", line 556, in handle_request
    response = await response
  File "venv/lib/python3.7/site-packages/sanic/app.py", line 259, in websocket_handler
    ws = await protocol.websocket_handshake(request, subprotocols)
  File "venv/lib/python3.7/site-packages/sanic/websocket.py", line 63, in websocket_handshake
    key = handshake.check_request(get_header)
  File "venv/lib/python3.7/site-packages/websockets/handshake.py", line 83, in check_request
    connection = parse_connection(headers.get('Connection', ''))
AttributeError: 'function' object has no attribute 'get'

[2018-07-18 11:39:06 +0100] - (sanic.access)[INFO][1:2]: GET ws://0.0.0.0:8000/feed  500 144
```

**Comment by ahopkins** [comment] 2018-07-18 11:44
I can confirm this as well. I have an instance that is running `websockets==5.0.1` that works fine. When websockets is upgraded to `6.0`, I get the same exception.

**Comment by jamesstidard** [comment] 2018-07-18 19:57
Looks like this has already been picked up by someone [on master](https://github.com/channelcat/sanic/blob/master/setup.py#L63), though on the latest [7.0 release](https://github.com/channelcat/sanic/blob/0.7.0/setup.py#L62) those checks are missing.

So this might be worth cherry picking those requirements into a point release to prevent those newly pip installing from getting a version of sanic with broken websockets, until sanic is updated to play nice with websockets>=6.0.

**Comment by jamesstidard** [comment] 2018-07-26 13:39
Equally, ran across some more things that may help others. `pytest-sanic` also has a [related issue](https://github.com/yunstanford/pytest-sanic/issues/17) around Sanic's websockets. Which requires to have `websockets<5` instead of `websockets<=6`.

`websockets` 4.x also uses `async` in its code which also makes it incompatible with Python 3.7's upgrade of async to a keyword. So currently I'm running this setup:

```yaml
# Pipfile
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
sanic = "*"
websockets = "<5.0"  # Sanic breaks on 6.0, pytest-sanic breaks on 5.0

[dev-packages]
pytest-sanic = "*"

[requires]
python_version = "3.6"  # websockets 4.0 uses async keyword from python 3.7
```

**Comment by james9837** [comment] 2018-08-02 15:26
I was able to get sanic master + websockets 6 to allow websocket connections with some [small tweaks to sanic/websockets.py](https://github.com/channelcat/sanic/compare/master...james9837:master#diff-2ec2363e3e214181e3e8ad803b5dc5b3).

**Comment by DanielClaudeBaeriswyl** [comment] 2018-08-03 13:40
the solution of james9837 worked for me!

**Comment by DanielClaudeBaeriswyl** [comment] 2018-08-06 08:29
will this fixed be merge to the version ?

**Comment by ahopkins** [comment] 2018-08-15 15:06
I spent my weekend rebuilding my phone websocket gateway to run in websockets alone scraping sanic. It was not fun, but necessary because of this.

**Comment by ashleysommer** [comment] 2018-08-15 21:17
@rubik I'm not a sanic project owner or collaborator. I can't do releases. People have been wanting a new release to for months. Nothing I can do about it.

**Comment by ahopkins** [comment] 2018-08-16 14:45
@garyo I appreciate that... but for a variety of reasons it's not an option for us.

**Comment by rubik** [comment] 2018-08-16 19:07
@ashleysommer Sorry, I was mistaken. Can we ping @r0fls then?

**Comment by ashleysommer** [comment] 2018-08-17 06:18
@ahopkins Im replying to your comment in this thread: https://github.com/channelcat/sanic/issues/1245#issuecomment-413761378

I have the same issue at my workplace. I use sanic in some projects, but its my own custom version, based on Sanic master with a bunch of patches applied.

Inspired by this, a few weeks ago I created a new project.
https://github.com/ashleysommer/pynecktie

PyNecktie is serious Sanic for serious business. It literally just relies on Sanic master, and inherits and extends every class with new names to make it look like its not Sanic. It has its own small test suite to ensure it is working correctly. Its aimed at devs who want to pitch this tool to their boss for use in an upcoming project, while hopefully avoiding the stigma of Sanic. It advertises it self as a "High Performance Python 3 Microservices Framework" rather than a HTTP server in an attempt to appeal to a non-tech-savvy audience.
The project is still in its infancy, I did have it pinned to sanic@0.7.0 but but yesterday I rebased it to sanic@master, and fixed a bunch of issues.
I intend to release regularly, whenever new features or fixes are added to Sanic.

**Comment by ahopkins** [comment] 2018-08-17 08:07
@ashleysommer looks awesome... I had even toyed with the idea of doing something similar. Checking it out now!

**Comment by DrPyser** [comment] 2018-09-19 21:00
I'm using python 3.7 for my project, and I want to use both sanic and websockets(for the websocket client). Problem is, pre-6.0 websockets client breaks in 3.7, so I need the 6.0 version. So I guess I can't use sanic(or use something else for the websocket client) until the next release.

**Comment by sjsadowski** [comment] 2018-09-25 19:12
This is addressed in PR#1304

**Comment by seemethere** [comment] 2018-10-23 22:13
Closing this with the merge of #1304

**Closed by seemethere** 2018-10-23 22:13 UTC
Labels: enhancement

**Comment by tadejmagajna** [comment] 2019-02-27 13:34
I can confirm problem persists with Python 3.7 and 3.6. I temporarily fixed the issue by downgrading websockets to `websockets==6.0`

**Comment by sjsadowski** [comment] 2019-02-27 14:50
The problem should not exist in 0.8.3 or 18.12LTS, can you provide example code you're using, along with platform so that I can test and verify?
