### ISSUE TITLE
Form Data not parsed properly

### ISSUE THREAD

**Issue by dmachi** [huge-success/sanic#1950] opened 2020-10-14 14:35 UTC
I have been testing with the streaming branch of Sanic. I am noticing that the form parsing doesn't work in this branch.

If the route has streaming set to True, then no form parsing happens.  If streaming is set to false, the form makes it to parsing, but are parsed incorrectly.

With application/x-www-form-urlencoded:
This form is parsed, but it turns all single value fields into arrays.
For example, this body:
`b'name=testfile.txt&type=text'`
ends up parsed as:
`{'name': ['testfile.txt'], 'type': ['text']}`
These two properties shouldn't have lists as values.

If I post with multipart/form-data, the body is:
`b'--206d46d982d43c1769c9907662ff4442\r\nContent-Disposition: form-data; name="name"; filename="name"\r\n\r\ntestfile.txt\r\n--206d46d982d43c1769c9907662ff4442\r\nContent-Disposition: form-data; name="type"; filename="type"\r\n\r\ntext\r\n--206d46d982d43c1769c9907662ff4442--\r\n'`

When the parser handles form-data, it ends up placing all of this information in request.files instead of taking the form data portions and putting them in request.form.

It is not yet clear to me if this only happens on the streaming branch or if it happens in the main branch too.  Am I doing something wrong here?

**Comment by sjsadowski** [comment] 2020-10-14 15:54
The first item (application/x-www-form-urlencoded) is a function of urllib.parse.parse_qs and works as intended by that library.

The second part (multipart/form-data) is happening because you are providing a filename, type, and body - as per the docs https://sanic.readthedocs.io/en/latest/sanic/request_data.html

**Comment by sjsadowski** [comment] 2020-10-14 17:04
I don't believe we provide a way to provide your own parser directly, but you could always parse the raw body on your own or you could monkey patch it. 

I think the array aspect is a function of the possibility of providing multiple fields of the same name, then they'd all be combined into that array. I honestly don't remember, though, I'd have to look at the docs.

As far as streaming goes, I'll need to dig in to find out what the expected behavior is. Not sure off the top of my head.

**Comment by dmachi** [comment] 2020-10-14 17:15
>I think the array aspect is a function of the possibility of providing multiple fields of the same name, then they'd all be combined into that array. I honestly don't remember, though, I'd have to look at the docs.

Yes, I think that is true.  Though the behavior I am used to is that if there is only one parameter with the name, it is a single value.  If there is more than one, it then becomes an array.  For example, in nodejs:

`$ node
Welcome to Node.js v12.13.0.
Type ".help" for more information.
> const qs = require('query-string')
> qs.parse("name=testfile.txt&type=text")
[Object: null prototype] { name: 'testfile.txt', type: 'text' }
> qs.parse("name=testfile.txt&type=text&name=foo")
[Object: null prototype] {
  name: [ 'testfile.txt', 'foo' ],
  type: 'text'
}
`
In any case, thanks for the info.  I've handled this in my codebase and will look into how I can do that more cleanly.

**Comment by ahopkins** [comment] 2020-10-14 20:21
Exactly. Sanic tries to strike a balance between providing sensible defaults to make development easy, and **NOT** being opinionated.

This is sort of one of those instances, as well as with query arguments. The lower level tooling provide lists because it *is possible* to have multiple keys.

Intuitively, it should be a single value. Technically, it is correct to be multiple. What should it be?

This might be a good place to implement `MultiDict` since it is already a dependency.

**Comment by sjsadowski** [comment] 2020-10-14 21:46
I'm going to go ahead and close this, though for my personal practices (and I chatted with someone who is a better dev than I am about this) the return value type should always stay the same. 

While it may be common to return a string value or an array value in the case of a single field vs multiple fields (or query params) it seems like it would be best practice to always return an array value, reducing the need for checking if there are one or more values to determine whether you need to get value or value[0] - you can always expect that if the key exists, the associated value is an array.

**Closed** 2020-10-14 21:49 UTC

**Comment by ashleysommer** [comment] 2020-10-14 22:58
I agree with @ahopkins and @sjsadowski
Returning a normal value when there's instance of the argument, and an array for multiple instances seems like it would lead to easily avoided bugs. And the easiest way to avoid those bugs is to always have the function return an array. If you only ever want the first instance of that argument, what I do in my code is `var param = next(iter(request.args['param']))`.

**Comment by dmachi** [comment] 2020-10-14 23:00
Yep, I'm fine with all this.  I wasn't advocating for a change, I just misunderstood the behavior.  Thanks.

**Comment by sjsadowski** [comment] 2020-10-15 02:40
@dmachi Yeah, I think that sometimes @ahopkins @ashleysommer and I end up chatting these things out when issues are brought up.

**Comment by ahopkins** [comment] 2020-10-15 03:47
> the return value type should always stay the same. 


While I get this, the input value (and type) are hidden from the dev, just like headers. It is a feature (and frankly the purpose) of frameworks to extract this information from http requests in a usable fashion. I do not, therefore, see a problem with MultiDict in this situation.

I do agree that sometimes having a single value and sometimes a list could lead to bugs. But I understand the sentiment that it seems like a flaw in Sanic when it always sends a list if you are not familiar with the spec. Not saying this is a strong enough reason to change. But it is worth documenting properly and the rationale.

**Comment by Tronic** [comment] 2020-10-15 08:16
MultiDict could be a good idea here. The type stays the same with that, too, but if you have multiple identically named fields, only one of them is returned, and `getall()` may be used when multiple entries are expected. Any ideas on how to implement that without breaking the existing API?

Another thing to note is that this type of form parser is not suitable for receiving large files. I'd love to see a streaming form parser some day. Such parser would not have field name lookups but an iterator or such that goes over the fields in the order that they were sent by client.

**Comment by ahopkins** [comment] 2020-10-15 14:01
I don't see how it could be not breaking without added complexity. I guess override weakref? But then get and weakref behave differently and that's terrible. I'd be in favor of tsbling it for 2021 as a breaking change.
