### ISSUE TITLE
20.3.0 changelog (404 NotFound)

### ISSUE THREAD

**Issue by Olegt0rr** [huge-success/sanic#1854] opened 2020-05-15 06:21 UTC
Version 20.3.0 released without
- Github [changelog](https://github.com/huge-success/sanic/blob/master/CHANGELOG.rst)
- Docs [changelog](https://sanic.readthedocs.io/en/latest/sanic/changelog.html)
- any news on [the site ](https://sanicframework.org/)

Please fix it

**Comment by andreymal** [comment] 2020-05-15 20:46
The Sanic community can't make releases properly for more than two years...

**Comment by omarryhan** [comment] 2020-05-16 04:35
Libraries like sanic_session are breaking and no one has a clue why. https://github.com/xen/sanic_session/issues/62. This is unacceptable for a major release.

**Comment by ashleysommer** [comment] 2020-05-16 06:25
@omarryhan 
The regression with `sanic_session` is known. It was reported to the Sanic gitter community very soon after the Sanic 20.3 release.

>no one has a clue why

That is not true. Actually we know exactly why `sanic_session` is broken. It is because the Sanic 20.3 release finally removed the deprecated request arbitrary attribute mechanism, in favor of the `request.ctx` mechanism that was introduced in Sanic 19.9.

The developers of `sanic_session` haven't yet caught up with the new release and issued a fix.

While we try to keep a stable API in Sanic, it is inevitable that with major releases come some internal changes. When this might potentially impact plugins, we move the old feature to deprecated for at least two release cycles before removing it, to give plugin developers time to work on a fix.

**Comment by omarryhan** [comment] 2020-05-16 07:30
Breaking a major API like this will have big consequences on the Sanic community. Not only it breaks all the session libraries out there, and the libraries that use the session libraries (e.g. auth libs), it also breaks most applications that make use of the request['session'] API internally and the request dict in general.

I've gone through these issues/PRs:
- https://github.com/huge-success/sanic/issues/1309
- https://github.com/huge-success/sanic/pull/1666
- https://github.com/huge-success/sanic/pull/1801

And I don't really see any critical issues that warrant a change like this. As far as I could tell, it was based on personal preference. But oh well, it's a bit late for that. I think the bigger issue is there being no Changelog for the latest release. You can't expect all Sanic users to be active in Gitter.

I understand that Sanic is an unfunded community project, and I appreciate all your work. So, if the release managers are busy, I'll be happy to chime in and help.

**Comment by omarryhan** [comment] 2020-05-16 07:43
About `sanic_session`, a fix will likely have to be backward incompatible and will break the API for all Sanic LTS users. I can think of a way or two how it can be fixed in a backward compatible manner, but it will be complex.

Frameworks like ExpressJS maintain `express-session` (the most popular session lib for ExpressJS) themeselves as well as other vital libraries in the ExpressJS community. This helps provide the stability needed for the community to grow. Maybe we should do something similar.

**Comment by ashleysommer** [comment] 2020-05-16 08:13
> Frameworks like ExpressJS maintain `express-session` (the most popular session lib for ExpressJS) themeselves as well as other vital libraries in the ExpressJS community. This helps provide the stability needed for the community to grow. Maybe we should do something similar.

I agree. At the moment `sanic-openapi` is the only Sanic plugin which is built and maintained by the Sanic organization (any maybe soon SanicJWT). All others are built and maintained by members of the sanic community. It would be amazing to have a whole suite of popular plugins provided by Sanic, each well maintained, and compatible with current Sanic, previous Sanic, and all supported LTS releases. If we all work together maybe we can make that happen.

**Comment by ashleysommer** [comment] 2020-05-16 08:18
@omarryhan @andreymal 
Just a reminder about our Sanic Community Forums [here](https://community.sanicframework.org/): https://community.sanicframework.org/

That might be a better platform than the Github Issue Tracker for discussing these topics further :).

**Comment by xen** [comment] 2020-05-18 14:18
@omarryhan @ashleysommer 

Fix for `sanic-session` was provided by @Paladiamors https://github.com/xen/sanic_session/pull/63 and new version has been released on PyPI. 

I don't have any active projects working on Sanic anymore. So I'm not uptoday with development of the Sanic Framework. If you make something like Sanic-Libs organization I will pass library maintenance to the community. For now, I'm helping community by accepting others pull requests and making new releases with some delay depending on my load. But doesn't have any personal interests in adding new features or anything else.

**Comment by swistakm** [comment] 2020-05-29 20:55
Hey, that's a real bummer there's no changelog at all for that release. And that's regardless of whether some changes were announced before or not. Same for deprecation.

**Comment by ahopkins** [comment] 2020-06-03 08:48
I sincerely apologize to everyone about this. Not that this is an excuse, but a number of us on the core team sort of got hit (just like everyone else in the world) this Spring because of the virus. Again, not an excuse. I am working on a changelog for 20.3, and we are going to change our contribution requirements so that every PR is accompanied with `towncrier` files (which we have had for a while now, just not enforced). I hope that 20.6 will be better.

**Comment by ahopkins** [comment] 2020-06-03 09:25
#1867

**Closed by ahopkins** 2020-06-03 09:25 UTC
