### ISSUE TITLE
each request taking a second

### ISSUE THREAD

**Issue by pradeeps** [huge-success/sanic#964] opened 2017-10-07 12:31 UTC
Hi guys,

Just few days ago, I came to know about Sanic and it felt really interesting project. So I decided to give it a try. It's not that it has issues or something. I am new to this. But just trying to understand why it takes 1 seconds for each request here. 

I am using Mac OS High Sierra. Virtualenv with py3, and pip install sanic.

server.py
```
from sanic import Sanic
from sanic.response import json

app = Sanic()

@app.route("/")
def test(request):
    return json({"hello":"works"})


if __name__=="__main__":
    app.run(host="0.0.0.0", port=8000)
```

client.py
```
import requests

i = 0
while True:
    r = requests.get('http://localhost:8000')
    print(r.text)
    if i == 1000: break
    i += 1
```

response from server:

```
2017-10-07 13:23:57 - (network)[INFO][127.0.0.1:55866]: GET http://localhost:8000/  200 17
2017-10-07 13:23:58 - (network)[INFO][127.0.0.1:55868]: GET http://localhost:8000/  200 17
2017-10-07 13:23:59 - (network)[INFO][127.0.0.1:55870]: GET http://localhost:8000/  200 17
2017-10-07 13:24:00 - (network)[INFO][127.0.0.1:55872]: GET http://localhost:8000/  200 17

```

I did a small program demo for hug (https://github.com/timothycrosley/hug) and this is the result 

```
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=801 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=802 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=803 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=804 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=805 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=806 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=807 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=808 HTTP/1.1" 200 30
127.0.0.1 - - [07/Oct/2017 13:30:13] "GET /happy_birthday?name=pradeep1&age=809 HTTP/1.1" 200 30
```

I am sorry if I am missing something here, but can someone help me understand why is this different? 

Thanks

**Comment by JoshYuJump** [comment] 2017-10-07 13:09
Did you have any proxy in the network settings?

**Comment by pradeeps** [comment] 2017-10-07 13:31
no, I dont have a proxy...both of the scripts were run with exactly same conditions

**Comment by yunstanford** [comment] 2017-10-07 13:32
Your code doesn't look very correct:
1. The client code is synchronous, it'd block itself.
2. `print` to terminal console is very expensive, because it does little/no I/O buffering, which means each individual `print` waits for the full write (i.e. display to output device) to complete.

**Comment by pradeeps** [comment] 2017-10-07 13:36
But I am using the same code to make a request .

import requests
import time

payload = {'name':'pradeep','age':'20'}

print(payload)
i = 0
while True:
    r = requests.get('http://127.0.0.1:8000/happy_birthday?name=pradeep1&age={}'.format(i)) # for Hug
    #r = requests.get('http://localhost:8000') # for Sanic
    print(r.text)
    if i == 1000: break
    i += 1

**Comment by yunstanford** [comment] 2017-10-07 13:57
Other than above two points,

First, That `2017-10-07 13:23:57` doesn't mean a lot, your benchmark code is not very correct, it only sends 1 request at one time, and async frameworks like `aiohttp` and `Sanic` are good at: 
1. handling more requests concurrently and
2. handling requests expensive I/Os...

if you really wanna benchmark it, try sth. like `wrk`.

**Comment by r0fls** [comment] 2017-10-08 22:22
Using your exact code I can't reproduce this. I get many requests occurring per second:

```
~/Documents/code $ python3 hello.py                                                                                            
2017-10-08 15:19:44 - (sanic)[DEBUG]:                                                                                              
                 ▄▄▄▄▄                                                                                                            
        ▀▀▀██████▄▄▄       _______________                                                                                              
      ▄▄▄▄▄  █████████▄  /                 \                                                                                        
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |                                                                                             
   ▀▀█████▄▄ ▀██████▄██ | _________________/                                                                                              
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/                                                                                                            
        ▀▀▀▄  ▀▀███ ▀       ▄▄                                                                                                          
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌                                                                                                    
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██                                                                                                 
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀                                                                                                       
▌    ▐▀████▐███▒▒▒▒▒▐██▌                                                                                                            
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀                                                                                                                 
          ▀▀█████████▀                                                                                                              
        ▄▄██▀██████▀█                                                                                                                 
      ▄██▀     ▀▀▀  █                                                                                                                   
     ▄█             ▐▌                                                                                                                
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄                                                                                                          
▌     ▐                ▀▀▄▄▄▀                                                                                                        
 ▀▀▄▄▀                                                                                                                          
                                                                                                                                   
2017-10-08 15:19:44 - (sanic)[INFO]: Goin' Fast @ http://0.0.0.0:8000                                                            
2017-10-08 15:19:44 - (sanic)[INFO]: Starting worker [38064]                                                                    
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64929]: GET http://localhost:8000/  200 17                                        
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64931]: GET http://localhost:8000/  200 17                                              
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64933]: GET http://localhost:8000/  200 17                                              
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64935]: GET http://localhost:8000/  200 17                                                
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64937]: GET http://localhost:8000/  200 17                                          
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64939]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64941]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64943]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64945]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64947]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64949]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64951]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64953]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64955]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64957]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64959]: GET http://localhost:8000/  200 17
2017-10-08 15:19:47 - (network)[INFO][127.0.0.1:64961]: GET http://localhost:8000/  200 17
```

Unless others can reproduce this, we'll need more information or to close this. I also suggest testing with `wrk` instead, as yunstanford suggested.

**Comment by x0v** [comment] 2017-10-13 06:13
hey @r0fls @yunstanford 
somewhat similar inputs I am looking for, as to what @pradeeps seeks.

I have asked somewhat similar question on [stackoverflow](https://stackoverflow.com/questions/46642171/developing-rest-apis-using-python-sanic) and got a feedback to utilise the number of cores in machine by using `workers=2` argument in `app.run`

the performance got an improvement in terms of number of requests but not really in terms of latency that I am seeing in wrk benchmark results.

here are my [benchmark results](https://jpst.it/166oe)

Let me know of it is not a right place to post stackoverflow link, I can explain my query again.

Thanks

**Comment by yunstanford** [comment] 2017-10-13 08:28
4000 connections ? Are you sure that you're going to handle 4000 connections simultaneously ?
It's very very expensive...

**Comment by x0v** [comment] 2017-10-14 07:00
absolutely, I need that. I just want to know how could i make my code more robust towards timeout errors in terms of leveraging sanic/python functionality ?

**Comment by yunstanford** [comment] 2017-10-17 22:15
1. 4000req/sec doesn't really mean 4000 connection
2. `handling 4000 connections simultaneously`  and directly by app (Sanic, aiohttp, flask etc.) process is very `expensive`, it has to cycle the connections there.
3. You may wanna put reverse proxy (nginx) in front of your app if you have so many long connections, you'd not expect a two worker app to handle that...

**Comment by shownb** [comment] 2017-10-21 12:16
@yunstanford @r0fls 
hello, I tested some codes in https://github.com/channelcat/sanic/tree/master/tests/performance 
just tested bottle and sanic.
I runed ab -n 10000 -c 10 http://192.168.2.110/
here is the results:
bottle
```
HTML transferred:       130000 bytes
Requests per second:    1677.17 [#/sec] (mean)
Time per request:       5.962 [ms] (mean)
Time per request:       0.596 [ms] (mean, across all concurrent requests)
Transfer rate:          281.71 [Kbytes/sec] received
```

sanic
```
HTML transferred:       130000 bytes
Requests per second:    526.89 [#/sec] (mean)
Time per request:       18.979 [ms] (mean)
Time per request:       1.898 [ms] (mean, across all concurrent requests)
Transfer rate:          53.00 [Kbytes/sec] received
```

the code is the same as **/tests/performance** . and I installed sanic with uvloop and ujson.
I can not understand, why bottle has a better performance.

**Comment by yunstanford** [comment] 2017-10-30 15:48
@shownb it might be because of logging, which is pretty expensive. try disable logging,
 ```python
app.run(log_config=None)
```

**Comment by sjsadowski** [comment] 2018-09-27 00:39
Closed due to lack of follow-up in 11 months.

**Closed** 2018-09-27 00:39 UTC
