### ISSUE TITLE
[Question]How can I only add middleware to one of the blueprint, without affecting the other blueprint

### ISSUE THREAD

**Issue by kolapapa** [huge-success/sanic#1138] opened 2018-02-22 09:48 UTC
I have a bp like this:
```python
bp_v0 = Blueprint('alert_v0', url_prefix='/v0')


@bp_v0.middleware('request')
async def auth_check(request):
    headers = request.headers
    token = headers.get('X_AUTH_TOKEN')
    if not token:
        return json({'status': 'not_authorized'}, 403)
    if headers.get('X_USER'):
        username = headers['X_USER']
        if gen_code(username) != token:
            return json({'status': 'not_authorized'}, 403)
    elif headers.get('X_SYSTEM'):
        system = headers['X_SYSTEM']
        if gen_code(system) != token:
            return json({'status': 'not_authorized'}, 403)
    else:
        return json({'status': 'not_authorized'}, 403)
```

and  I have another bp, like this:
```python
root = Blueprint('root')

@root.route('/')
async def index(request):
    LOG.info('index log.')
    return text('success')
```

setup blueprint:
```python
def setup_blueprints(app):
    app.blueprint(root)

    from server.apps.api.v0.alert import bp_v0 as alert_v0
    app.blueprint(alert_v0)
```

```shell
➜  ~ http 0.0.0.0:9000/
HTTP/1.1 403 Forbidden
Connection: close
Content-Length: 27
Content-Type: application/json

{
    "status": "not_authorized"
}
```

### How can I only add middleware to one of the blueprint, without affecting the other blueprint

![image](https://user-images.githubusercontent.com/17918689/36532427-aafcdeea-17fb-11e8-9c9c-4cbad24157b6.png)
> Using blueprints allows you to also register middleware `globally`. 

What if I don't want to set up as global?

**Comment by kolapapa** [comment] 2018-02-22 10:17
I have a way to judge path. But I don't think it's beautiful enough.
```python
bp_v0 = Blueprint('alert_v0', url_prefix='/v0')

@bp_v0.middleware('request')
async def auth_check(request):
    path = request.path
    if path.startswith('/v0/'):
        pass

**Comment by andreheringer** [comment] 2018-02-22 19:19
I'm having the same problem, the documentation says that the middleware defined in a blueprint will be used globally but I want it to be applied  only inside the blueprint.

**Comment by r0fls** [comment] 2018-03-25 07:40
This is an open issue already: https://github.com/channelcat/sanic/issues/37

Ideally it would be configurable.

**Comment by sjsadowski** [comment] 2018-09-27 00:08
Closing as dupe of #37 per previous discussion

**Closed by sjsadowski** 2018-09-27 00:08 UTC
Labels: duplicate
