### ISSUE TITLE
Lots of ResourceWarnings when testing

### ISSUE THREAD

**Issue by WilliamMayor** [huge-success/sanic#754] opened 2017-05-28 14:28 UTC
When I run my test suite I see lots of ResourceWarnings like this:

    /usr/local/lib/python3.6/site-packages/sanic/server.py:471: ResourceWarning: unclosed resource <TCPTransport closed=False reading=True 0x31c3088>
      loop.close()

Is this something I'm doing wrong? I'm afraid I don't know the sanic code well enough yet to debug myself.

Thanks for your help!

**Comment by furious-luke** [comment] 2017-06-23 13:27
+1
I'm getting the same errors. It's strange, my tests were not producing them for a long time, but just recently they started appearing.

**Comment by carver** [comment] 2018-10-16 23:36
You'll probably find more helpful results online with `ResourceWarning: unclosed transport <_SelectorSocketTransport ...`.

The warning from OP is produced by `uvloop` which seems less common. It looks like roughly the solution is to do an `await asyncio.sleep(0)` in between closing a transport and letting it get garbage collected.

**Comment by yunstanford** [comment] 2018-10-17 00:08
Yeah, the reason is: after calling transport.close() asyncio needs for extra loop iteration for actual closing. and It's by design. After adding `await asyncio.sleep(0)` just before loop closing should be able to swipe warnings.

**Closed** 2018-10-17 05:05 UTC
Labels: needs investigation
